version: "3"

volumes:
  symfony_db:

networks:
  symfony:

services:
  nginx:
    build: docker/nginx
    image: vegas-nginx-dev-image
    cap_drop: [all]
    cap_add: [chown, setgid, setuid, dac_override, net_bind_service]
    container_name: vegas-nginx-dev
    volumes:
      - ./:/var/www/vegas:cached
    ports:
      - 8001:80
    networks:
      - symfony
  php:
    build: docker/php
    image: vegas-php-dev-image
    cap_drop: [all]
    cap_add: [chown, setgid, setuid, dac_override]
    container_name: vegas-php-dev
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/project_db
    volumes:
      - ./:/var/www/vegas:cached
    networks:
      - symfony
  db:
    image: mysql:5.7
    cap_drop: [all]
    cap_add: [chown, setgid, setuid, dac_override]
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - symfony_db:/var/lib/mysql:cached
    ports:
      - 3311:3306
    networks:
      - symfony
